### ISSUE TITLE
Add scrolling to sidebar with many steps

### ISSUE THREAD

**Issue by Alex-Sokolov** [amoffat/bootstrap-application-wizard#30]
When wizard have many steps, sidebar showed ugly. To fix this need to expand container style with rule:

``` css
.wizard-nav-container {
    overflow-y: scroll;
}
```
